# This script creates the Windows-side symbolic links required by the native
# Alacritty application when chezmoi and the authoritative configuration are
# managed exclusively inside WSL2.
#
# HOW TO RUN
# ----------
# 1. Start the target WSL2 distribution at least once so that its filesystem is
#    available through \\wsl.localhost.
# 2. Open PowerShell on the Windows host, not a shell inside WSL2.
# 3. Prefer a non-elevated PowerShell session when Windows Developer Mode is
#    enabled. Otherwise, start PowerShell with "Run as administrator" because
#    creating symbolic links may require elevated privileges.
# 4. Run the script with:
#
#      powershell.exe -ExecutionPolicy Bypass -File .\setup-alacritty-wsl-links.ps1
#
#    From PowerShell 7, `pwsh.exe` can be used instead of `powershell.exe`.
#
# RESULT
# ------
# The script creates these Windows-side links:
#
#   %APPDATA%\alacritty\alacritty.toml
#     -> \\wsl.localhost\<distro>\<wsl-home>\.config\alacritty\alacritty.toml
#
#   %APPDATA%\alacritty\themes
#     -> \\wsl.localhost\<distro>\<wsl-home>\.config\alacritty\themes
#
# This allows Alacritty on Windows to use the files generated by chezmoi inside
# WSL2 without maintaining a second copy of the configuration or theme files.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Detect the default WSL distribution from the per-user WSL registry state.
# This is more reliable than parsing `wsl.exe --list --verbose`, whose display
# output may be localized and marks the default distribution only for humans.
$LxssRoot = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss"

if (-not (Test-Path -LiteralPath $LxssRoot)) {
    throw "WSL registry configuration was not found under $LxssRoot."
}

$DefaultDistributionId = (
    Get-ItemProperty -LiteralPath $LxssRoot -Name "DefaultDistribution"
).DefaultDistribution

if ([string]::IsNullOrWhiteSpace($DefaultDistributionId)) {
    throw @"
WSL does not report a default distribution.
Install a distribution or select one with:
  wsl.exe --set-default <DistributionName>
"@
}

$DefaultDistributionKey = Join-Path $LxssRoot $DefaultDistributionId
$Distro = (
    Get-ItemProperty -LiteralPath $DefaultDistributionKey -Name "DistributionName"
).DistributionName

if ([string]::IsNullOrWhiteSpace($Distro)) {
    throw "The default WSL distribution name could not be resolved."
}

# Alacritty on Windows reads its configuration from this directory.
$WindowsConfigDir = Join-Path $env:APPDATA "alacritty"

Write-Host "Detected default WSL distribution: '$Distro'"

# Verify that the requested distribution exists before attempting to resolve
# paths. The comparison trims the carriage-return characters sometimes emitted
# by wsl.exe when its output is consumed by PowerShell.
$InstalledDistros = @(
    wsl.exe --list --quiet |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ }
)

if ($Distro -notin $InstalledDistros) {
    throw @"
WSL distribution '$Distro' was not found.
Run 'wsl.exe --list --quiet' and update `$Distro in this script with the exact name.
"@
}

# Ask the selected distribution for its Linux home directory. This avoids
# hardcoding the WSL username or assuming that the home directory is /home/user.
$WslHome = (
    wsl.exe -d $Distro -- sh -lc 'printf %s "$HOME"'
).Trim()

if ([string]::IsNullOrWhiteSpace($WslHome)) {
    throw @"
The Linux home directory could not be resolved for '$Distro'.
Start the distribution manually with 'wsl.exe -d $Distro' and retry.
"@
}

# Build the UNC path exposed by WSL2. Alacritty itself runs on Windows, so the
# Windows links must target a path visible from the Windows host.
$WslConfigDir = "\\wsl.localhost\$Distro$WslHome\.config\alacritty"
$WslConfigFile = Join-Path $WslConfigDir "alacritty.toml"
$WslThemesDir = Join-Path $WslConfigDir "themes"

Write-Host "Resolved WSL Alacritty directory: $WslConfigDir"

# Store the detected distribution in the machine-local chezmoi configuration.
# The Alacritty template reads this value only inside WSL2. Shared defaults stay
# in .chezmoidata.toml, while host-specific values belong under [data] here.
$ChezmoiConfigFile = "\\wsl.localhost\$Distro$WslHome\.config\chezmoi\chezmoi.toml"

function Set-ChezmoiTomlDataValue {
    param(
        [Parameter(Mandatory = $true)]
        [string] $ConfigPath,

        [Parameter(Mandatory = $true)]
        [string] $Key,

        [Parameter(Mandatory = $true)]
        [string] $Value
    )

    if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
        throw @"
The machine-local chezmoi configuration was not found:
  $ConfigPath

Initialize chezmoi inside the default WSL distribution before running this script.
"@
    }

    # Read and update only the requested scalar key in the [data] table. The
    # operation preserves all unrelated settings and creates [data] when absent.
    $Lines = [System.Collections.Generic.List[string]]::new()
    [System.IO.File]::ReadAllLines($ConfigPath) | ForEach-Object { $Lines.Add($_) }

    $DataStart = -1
    $DataEnd = $Lines.Count

    for ($Index = 0; $Index -lt $Lines.Count; $Index++) {
        if ($Lines[$Index] -match '^\s*\[data\]\s*$') {
            $DataStart = $Index
            for ($Next = $Index + 1; $Next -lt $Lines.Count; $Next++) {
                if ($Lines[$Next] -match '^\s*\[[^]]+\]\s*$') {
                    $DataEnd = $Next
                    break
                }
            }
            break
        }
    }

    # Escape characters that have a special meaning in a TOML basic string.
    $TomlValue = $Value.Replace('\', '\\').Replace('"', '\"')
    $Assignment = "$Key = `"$TomlValue`""
    $Changed = $false

    if ($DataStart -ge 0) {
        for ($Index = $DataStart + 1; $Index -lt $DataEnd; $Index++) {
            if ($Lines[$Index] -match "^\s*$([regex]::Escape($Key))\s*=") {
                if ($Lines[$Index] -ne $Assignment) {
                    $Lines[$Index] = $Assignment
                    $Changed = $true
                }
                break
            }
        }

        if (-not ($Lines | Select-Object -Skip ($DataStart + 1) -First ($DataEnd - $DataStart - 1) | Where-Object { $_ -match "^\s*$([regex]::Escape($Key))\s*=" })) {
            $Lines.Insert($DataEnd, $Assignment)
            $Changed = $true
        }
    }
    else {
        if ($Lines.Count -gt 0 -and $Lines[$Lines.Count - 1] -ne "") {
            $Lines.Add("")
        }
        $Lines.Add("[data]")
        $Lines.Add($Assignment)
        $Changed = $true
    }

    if (-not $Changed) {
        Write-Host "Chezmoi data already correct: $Key = '$Value'"
        return
    }

    # Keep a timestamped backup before changing the machine-local configuration.
    $BackupPath = "$ConfigPath.$(Get-Date -Format 'yyyyMMdd-HHmmss').bak"
    Copy-Item -LiteralPath $ConfigPath -Destination $BackupPath

    # Write UTF-8 without a BOM for consistent behavior in Windows PowerShell 5.1
    # and PowerShell 7. TOML accepts UTF-8, and chezmoi can read it directly.
    $Utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllLines($ConfigPath, $Lines, $Utf8WithoutBom)

    Write-Host "Updated chezmoi machine data: $Key = '$Value'"
    Write-Host "Backup created: $BackupPath"
}

Set-ChezmoiTomlDataValue `
    -ConfigPath $ChezmoiConfigFile `
    -Key "wsl_distribution" `
    -Value $Distro

# Render the Alacritty configuration after updating chezmoi.toml. This ordering
# avoids a first-run failure where the template references wsl_distribution
# before the machine-local value exists.
Write-Host "Applying the Alacritty configuration inside WSL2..."
wsl.exe -d $Distro -- sh -lc 'chezmoi apply ~/.config/alacritty/alacritty.toml'

if ($LASTEXITCODE -ne 0) {
    throw @"
chezmoi failed to apply the Alacritty configuration inside '$Distro'.
Open the distribution and run:
  chezmoi execute-template < ~/Repos/github.com/mocer/dotfiles/dot_config/alacritty/private_alacritty.toml.tmpl
"@
}

# Fail before modifying Windows files if chezmoi has not generated the expected
# Alacritty configuration inside WSL2.
if (-not (Test-Path -LiteralPath $WslConfigFile -PathType Leaf)) {
    throw @"
The WSL Alacritty configuration was not found:
  $WslConfigFile

Inside WSL2, run:
  chezmoi apply ~/.config/alacritty/alacritty.toml

Then verify:
  test -f ~/.config/alacritty/alacritty.toml
"@
}

# The themes directory is linked separately because alacritty.toml imports the
# theme using a path relative to the Windows-side configuration directory:
#
#   import = ["themes/themes/enfocado_dark.toml"]
if (-not (Test-Path -LiteralPath $WslThemesDir -PathType Container)) {
    throw @"
The WSL Alacritty themes directory was not found:
  $WslThemesDir

Ensure the themes repository or managed theme files exist under:
  ~/.config/alacritty/themes
"@
}

# Ensure that the Windows configuration directory exists. This operation is
# idempotent and does not modify existing files inside the directory.
New-Item -ItemType Directory -Force -Path $WindowsConfigDir | Out-Null

function Set-SymbolicLink {
    param(
        [Parameter(Mandatory = $true)]
        [string] $LinkPath,

        [Parameter(Mandatory = $true)]
        [string] $TargetPath
    )

    # If the expected symbolic link already exists and points to the correct
    # target, leave it unchanged. This makes the script safe to run repeatedly.
    if (Test-Path -LiteralPath $LinkPath) {
        $ExistingItem = Get-Item -LiteralPath $LinkPath -Force

        if ($ExistingItem.LinkType -eq "SymbolicLink") {
            $ExistingTargets = @($ExistingItem.Target)
            if ($TargetPath -in $ExistingTargets) {
                Write-Host "Symbolic link already correct: $LinkPath"
                return
            }
        }

        # Do not silently overwrite a real file or directory. An existing local
        # configuration may contain changes that have not yet been moved into
        # the chezmoi-managed WSL source.
        throw @"
Cannot create the symbolic link because this path already exists:
  $LinkPath

Back up or remove it manually, then run the script again.
Expected target:
  $TargetPath
"@
    }

    try {
        New-Item `
            -ItemType SymbolicLink `
            -Path $LinkPath `
            -Target $TargetPath | Out-Null

        Write-Host "Created symbolic link:"
        Write-Host "  $LinkPath"
        Write-Host "  -> $TargetPath"
    }
    catch {
        throw @"
Failed to create the symbolic link:
  $LinkPath
  -> $TargetPath

Possible causes:
- Windows Developer Mode is disabled and PowerShell is not elevated.
- The WSL distribution is stopped or its \\wsl.localhost path is unavailable.
- Endpoint security policy blocks symbolic links to UNC paths.
- A parent directory prevents the current user from creating links.

Try the following:
1. Enable Windows Developer Mode and retry from a normal PowerShell session.
2. Alternatively, run PowerShell as Administrator.
3. Start WSL with 'wsl.exe -d $Distro' and confirm this path opens:
     $WslConfigDir
4. Inspect the original error below:
     $($_.Exception.Message)
"@
    }
}

# Link the main configuration file used by native Alacritty on Windows.
Set-SymbolicLink `
    -LinkPath (Join-Path $WindowsConfigDir "alacritty.toml") `
    -TargetPath $WslConfigFile

# Link the entire themes directory so relative imports behave identically on
# Windows, macOS, and native Linux.
Set-SymbolicLink `
    -LinkPath (Join-Path $WindowsConfigDir "themes") `
    -TargetPath $WslThemesDir

Write-Host "Verifying links..."

$ConfigLink = Get-Item `
    -LiteralPath (Join-Path $WindowsConfigDir "alacritty.toml") `
    -Force

$ThemesLink = Get-Item `
    -LiteralPath (Join-Path $WindowsConfigDir "themes") `
    -Force

$ExpectedTheme = Join-Path $WindowsConfigDir "themes\themes\enfocado_dark.toml"

if ($ConfigLink.LinkType -ne "SymbolicLink") {
    throw "The Alacritty configuration path is not a symbolic link."
}

if ($ThemesLink.LinkType -ne "SymbolicLink") {
    throw "The Alacritty themes path is not a symbolic link."
}

if (-not (Test-Path -LiteralPath $ExpectedTheme -PathType Leaf)) {
    throw @"
The links were created, but the imported theme cannot be resolved:
  $ExpectedTheme

Check that the theme exists inside WSL2 at:
  $WslThemesDir\themes\enfocado_dark.toml
"@
}

Write-Host ""
Write-Host "Alacritty WSL2 links configured successfully."
Write-Host "Windows configuration: $WindowsConfigDir"
Write-Host "WSL source:            $WslConfigDir"
Write-Host ""
Write-Host "If Alacritty still does not load the configuration:"
Write-Host "- Restart Alacritty after ensuring the WSL distribution is running."
Write-Host "- Run 'alacritty.exe -vv' from PowerShell and inspect the config paths."
Write-Host "- Confirm that wsl.exe can start '$Distro' without an interactive prompt."
Write-Host "- Confirm that the mise Fish shim exists inside WSL2."
